### ISSUE TITLE
Use a decent license?

### ISSUE THREAD

**Issue by equwal** [sheepduke/emacs-settings#1]
Hello, your code is not licensed. Would you please consider licensing it? Maybe with the GNU GPL v3? Might be possible to get some stuff into Emacs if you did this. Particularly it would be nice to have the lisp font-lock stuff in.

**Comment by sheepduke** [comment]
On 2019-06-27 15:49, Spenser Truex <notifications@github.com> wrote:
> Hello, your code is not licensed. Would you please consider licensing it? Maybe with the GNU GPL v3?
>
Hi,

I have made this project "unlicensed" since some ideas are grabbed here
and there from the Internet.

Maybe putting it into the public domain would potentially help more
people.

Is this acceptable for you?

I will rethink of it if you insist to have a GPLv3 license.

By the way, I am curious that what function got your attention?

Cheers.

**Comment by equwal** [comment]
The lisp font lock stuff really should be in `lisp-mode` in my opinion (built into Emacs). If you could GNU GPL v3 just that portion (put it in a different repo maybe?), or the whole thing here, then it would be much easier to get it in, especially with your consent. Technically any compatible free license (with GNU GPL v3, which is what Emacs uses) should work.

Lisp font lock stuff:
https://github.com/sheepduke/emacs-settings/blob/master/settings/d2-dev-lisp.el

**Comment by sheepduke** [comment]
On 2019-06-28 18:01, Spenser Truex <notifications@github.com> wrote:
> The lisp font lock stuff really should be in `lisp-mode` in my opinion (built into Emacs). If you could GNU GPL v3 just that portion (put it in a different repo maybe?) then it would be much easier to get it in, especially with your consent.
>
Well, I can do that. But there is one more problem to solve.

Actually the current keyword list has a problem that all symbols (except
variables) are added to `font-lock-function-name-face`, which is
incorrect for types.

I can separate them and make a new list in a new repo early next week.

What do you think?

P.S. Just out of curiosity: why is GPL v3 more convenient than Public Domain?

**Comment by equwal** [comment]
> On 2019-06-28 18:01, Spenser Truex ***@***.***> wrote: The lisp font lock
> stuff really should be in `lisp-mode` in my opinion (built into Emacs). If you
> could GNU GPL v3 just that portion (put it in a different repo maybe?) then it
> would be much easier to get it in, especially with your consent. Well, I can
> do that. But there is one more problem to solve. Actually the current keyword
> list has a problem that all symbols (except variables) are added to
> `font-lock-function-name-face`, which is incorrect for types. I can separate
> them and make a new list in a new repo early next week. What do you think?

Yeah that sounds great, I just discovered this bug on accident when adding `nil` and `t` to the variables.

> P.S. Just out of curiosity: why is GPL v3 more convenient than Public Domain?

I just think that a real license (e.g. in a LICENSE file) that is compatible with GNU GPL
v3 is needed. I suggested just doing the GNU GPL v3, but you can do whatever you
like really.

**Comment by sheepduke** [comment]
On 2019-06-29 16:58, Spenser Truex <notifications@github.com> wrote:
> Yeah that sounds great, I just discovered this bug on accident when adding `nil` and `t` to the variables.
>
I have refined the symbol list. I found more bugs so I just re-did it.

Now we have different faces: functions, variables, types and built-in
symbols.

> I just think that a real license (e.g. in a LICENSE file) that is compatible with GNU GPL
> v3 is needed. I suggested just doing the GNU GPL v3, but you can do whatever you
> like really.
>
So which of the following way is more convenient for you?

1. Another repository containing only Lisp symbols, with GNU GPL v3 license.
2. I change *this* repository to GNU GPL v3.

**Comment by equwal** [comment]
I see that you put in a LICENSE file, I think it is good enough as is, thanks. I'm going to close now.

**Comment by sheepduke** [comment]
@equwal Someone on Reddit suggested me to put it into Emacs.

Are you doing the same thing? If not I will try to make a PR or so...

**Comment by equwal** [comment]
The problem with it as it is now is that it hangs, since using regular expressions for this is too inefficient.

**Comment by sheepduke** [comment]
This is strange because if my understanding is correct, the build-in `lisp-mode` file also uses regex to match keywords.

Do you have any advice to enhance it?

**Comment by equwal** [comment]
> This is strange because if my understanding is correct, the build-in `lisp-mode` file also uses regex to match keywords.
> 
> Do you have any advice to enhance it?

After going back and trying to reproduce it, I was not able to. It must have been another issue in my Emacs. Closing this.
